### ISSUE TITLE
Where are the stylesheets?

### ISSUE THREAD

**Issue by xeoncross** [tryy3/webbforum#1]
Looks like the css and js directories are missing. Are their any plans to add those (or at least shell style sheets)?

**Comment by tryy3** [comment]
It seems that I added the content folder to .gitignore when I pushed this project.

I created this project when for a project I had in college so I haven't worked on it in a while.
But I'll check if I still have the original files when I get home.

**Comment by tryy3** [comment]
Luckily I had the original files on my computer.

I have now uploaded the content folder.
I also attempted to start it but for some reason the XSRF token check broke, so I made a few small changes to disable it, so that I could register and login.

But the content folder is uploaded now and it seems to be working.

**Comment by xeoncross** [comment]
Thanks, glad to hear you still had a copy and thanks for sharing this project.

![Screen Shot 2020-01-23 at 1 28 05 PM](https://user-images.githubusercontent.com/56460/73016854-4c4a5880-3de4-11ea-8a65-fc10d297e95f.png)
